# Generated by Django 3.0.3 on 2020-05-05 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stats', '0003_auto_20200428_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentFrequency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content_id', models.IntegerField()),
                ('content_type', models.IntegerField()),
                ('frequency', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['content_type', 'frequency'],
            },
        ),
    ]
