# Generated by Django 3.0.3 on 2020-03-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (0, 'Female')]),
        ),
    ]
