# Generated by Django 3.0.3 on 2020-05-07 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200405_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailByProvider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('provider', models.IntegerField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
