# Generated by Django 3.0.3 on 2020-03-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20200328_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='access_code',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
