# Generated by Django 3.0.3 on 2020-04-28 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_auto_20200405_2127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classhasstudent',
            options={'ordering': ['classroom', 'date_joined', 'student']},
        ),
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['date_created']},
        ),
    ]
