# Generated by Django 3.0.3 on 2020-04-28 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_auto_20200410_1712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materials',
            options={'ordering': ['classroom', 'date_uploaded', 'name']},
        ),
    ]
